### ISSUE TITLE
Swamp Palace big chest accessible with BK in back

### ISSUE THREAD

**Issue by emerald000** [codemann8/alttpr_codetracker_codemann8#1]
In non-keysanity, the Swamp Palace big chest shows up as accessible without the hookshot. The BK is possibly stuck in the back and inaccessible.

![](https://i.imgur.com/LOhUW6j.png)

**Comment by codemann8** [comment]
Thanks for the feedback.  This is, of course, the risk of having/showing logic for ALL the chests when not under keysanity, it will be impossible to show exactly what you are able to get due to key placements. My general rule of thumb is, it should only show as yellow if it is a sequence break (out of logic) to get it.  I like to think of the white text as "in logic" and free to grab without worry of logic, of course, if you are able to.  There is the added bonus on this tracker of seeing if you have the BK in non-keysanity, so you can at least piece that together before going to that location.

If you do see other scenarios where this doesn't follow this pattern, please report that too, there is bound to be a number of them.

**Comment by emerald000** [comment]
Alright, makes sense.
