### ISSUE TITLE
Crosskeys logic for pyramid ledge

### ISSUE THREAD

**Issue by Zehir** [codemann8/alttpr_codetracker_codemann8#28]
Hello, when you have a Crosskeys seed and mark the pyramid hole as the sanctuary the pyramid ledge item is not marked in green but it's accessible when loading from the sanctuary the walk to the item in bunny.

Sample seed : https://alttpr.com/en/h/xry09zLKG5

Tracker settings :
Dungeon Items : All 4 selected
Entranche Shuffle : Entrance

![image](https://user-images.githubusercontent.com/845225/145799753-e4faf0d1-3287-4b79-ac0d-7026cbe19da7.png)

I don't know if this is in 'logic' but could be in yellow in that case.

Some entrances can be accessible too :

- Dark Sahasrahla
- Dark Trees Fairy
- East Storyteller Cave
- POD entance ? Maybe, I don't know if the monkey talk when you are in rabbit

**Comment by codemann8** [comment]
This is an intentional function. As it is often the case where you might be able to determine that Pyramid Hole is either not needed, or you mark is as something (because you found the other 7 dropdown holes) it is important to be able to mark this dropdown without marking that you have access to the area. This is easily resolved by immediately checking and marking pyramid ledge item immediately following exiting the pyramid hole location.
